version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "jkl"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1imm0k84hljnc"
s3_prefix = "jkl"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

