AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
# TODO Handler def
  CheckAgeFunction:
    Type: AWS::Serverless::Function
    Properties: 
      CodeUri: src/lib/
      Handler: take-age.AgeTakeHandler
      Runtime: nodejs12.x

  KidsMoviesFunction:
    Type: AWS::Serverless::Function
    Properties: 
      CodeUri: src/lib/
      Handler: kids-movies.KidsMoviesHandler
      Runtime: nodejs12.x

  AdultsMoviesFunction:
    Type: AWS::Serverless::Function
    Properties: 
      CodeUri: src/lib/
      Handler: all-movies.AllMoviesHandler
      Runtime: nodejs12.x

# TODO machine def
  
  MoviesStatemachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: state-mac-def/movie-flow.json
      DefinitionSubstitutions:
        CheckAgeFunctionArn: !GetAtt CheckAgeFunction.Arn
        KidsMoviesFunctionArn: !GetAtt KidsMoviesFunction.Arn
        AllMoviesFunctionArn: !GetAtt AdultsMoviesFunction.Arn
      Events:
        StateMac:
          Type: Api
          Properties:
            Path: /movies
            Method: POST
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref CheckAgeFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref KidsMoviesFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref AdultsMoviesFunction




# TODO congito def





















Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  
